package projeto.com.negocio;
// Generated 02/08/2019 20:08:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name="material"
    ,schema="public"
)
public class Material  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Integer quantidade;
     private BigDecimal largura;
     private BigDecimal comprimento;
     private BigDecimal altura;

    public Material() {
    }

	
    public Material(int id) {
        this.id = id;
    }
    public Material(int id, String descricao, Integer quantidade, BigDecimal largura, BigDecimal comprimento, BigDecimal altura) {
       this.id = id;
       this.descricao = descricao;
       this.quantidade = quantidade;
       this.largura = largura;
       this.comprimento = comprimento;
       this.altura = altura;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="largura", precision=5)
    public BigDecimal getLargura() {
        return this.largura;
    }
    
    public void setLargura(BigDecimal largura) {
        this.largura = largura;
    }

    
    @Column(name="comprimento", precision=5)
    public BigDecimal getComprimento() {
        return this.comprimento;
    }
    
    public void setComprimento(BigDecimal comprimento) {
        this.comprimento = comprimento;
    }

    
    @Column(name="altura", precision=5)
    public BigDecimal getAltura() {
        return this.altura;
    }
    
    public void setAltura(BigDecimal altura) {
        this.altura = altura;
    }




}


