package projeto.com.apresentacao;

import java.awt.Event;
import java.util.List;
import javax.swing.JOptionPane;
import projeto.com.dao.DaoCalculo;
import projeto.com.dao.DaoMaterial;
import projeto.com.negocio.Material;

/**
 *
 * @author Douglas
 */
public class DlgBuscaMaterial extends javax.swing.JDialog {

    DlgCalculo ifrCalculo;

    public DlgBuscaMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarMaterialidades();
    }

    public DlgBuscaMaterial(java.awt.Frame parent, boolean modal, DlgCalculo ifrCalculo) {
        super(parent, modal);
        initComponents();
        this.ifrCalculo = ifrCalculo;
        listarMaterialidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        tfdPesquisa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Descrição", "Classe", "Condutividade", "Calor", "FatorSolar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterial);
        if (tblMaterial.getColumnModel().getColumnCount() > 0) {
            tblMaterial.getColumnModel().getColumn(0).setResizable(false);
            tblMaterial.getColumnModel().getColumn(1).setResizable(false);
            tblMaterial.getColumnModel().getColumn(2).setResizable(false);
            tblMaterial.getColumnModel().getColumn(3).setResizable(false);
            tblMaterial.getColumnModel().getColumn(4).setResizable(false);
            tblMaterial.getColumnModel().getColumn(5).setResizable(false);
        }

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tfdPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPesquisaActionPerformed(evt);
            }
        });
        tfdPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdPesquisaKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfdPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked
        if (evt.getClickCount() == 2) {
            definirValores();
        }
    }//GEN-LAST:event_tblMaterialMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (tblMaterial.getSelectedRow() != -1) {
        definirValores();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma Materialidade!");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void tfdPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPesquisaKeyReleased
        if (evt.getKeyCode() == Event.ENTER) {
            DaoMaterial.pesquisaMaterialDlg(tblMaterial, tfdPesquisa.getText(), "Vidro", "Câmara de ar");
        }
    }//GEN-LAST:event_tfdPesquisaKeyReleased

    private void tfdPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPesquisaActionPerformed

    }//GEN-LAST:event_tfdPesquisaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       DaoMaterial.pesquisaMaterialDlg(tblMaterial, tfdPesquisa.getText(), "Vidro", "Câmara de ar");
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void definirValores() {
        List resultado = null;
        Material material = new Material();
        String idString = String.valueOf(tblMaterial.getValueAt(tblMaterial.getSelectedRow(), 0));
        int codigoTabela = Integer.parseInt(idString);

        resultado = DaoMaterial.buscaIdMaterial(codigoTabela);

        for (Object o : resultado) {
            Material mat = (Material) o;
            material.setDescricao(mat.getDescricao());
            material.setCalor(mat.getCalor());
            material.setDencidade(mat.getDencidade());
            material.setCor(mat.getCor());
            material.setCondutividade(mat.getCondutividade());
            material.setFatorsolar(mat.getFatorsolar());
        }
        ifrCalculo.definirValorMaterial(String.valueOf(codigoTabela), material.getDescricao());
        dispose();
    }
    
    public void listarMaterialidades(){
        if(DaoCalculo.verificarTipoCalculo(ifrCalculo.CALCULO.getId())){
            DaoMaterial.listarMaterial(tblMaterial);
        }else{
            DaoMaterial.listarMaterialDlg(tblMaterial, "Vidro", "Câmara de ar");
            btnBuscar.setEnabled(false);
            tfdPesquisa.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField tfdPesquisa;
    // End of variables declaration//GEN-END:variables
}
