/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.com.apresentacao;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import projeto.com.dao.DaoDashboard;

/**
 *
 * @author ruiwa
 */
public class IfrDashboards extends javax.swing.JInternalFrame {
    
    public IfrDashboards(JDesktopPane jdp, String projeto) {
        
        DaoDashboard dash = new DaoDashboard();
        
        
        JFreeChart barchart = ChartFactory.createBarChart("Projetos e valor do Qfo total dos comodos", "Comodos","Valor do QFO", dash.buscaProjeto(projeto), PlotOrientation.VERTICAL, true, true, false);
        ChartPanel cp = new ChartPanel(barchart);

        JInternalFrame jif = new JInternalFrame(
            "Graficos Projeto", true, true, true, true);
        
        jif.add(cp);
        jif.pack();
        jif.setLocation(0, 60);
        jif.setSize(600, 300);
        jif.setVisible(true);
        
                      
        JFreeChart chart2 = ChartFactory.createBarChart("Quatidade de face dos comodos", "Comodos", "Face", dash.buscaFace(projeto), PlotOrientation.VERTICAL, true, true, false);
        ChartPanel cp2 = new ChartPanel(chart2);

        JInternalFrame jif2 = new JInternalFrame(
            "Quantidade de face", true, true, true, true);
        
        jif2.add(cp2);
        jif2.pack();
        jif2.setLocation(601, 60);
        jif2.setSize(600, 300);
        jif2.setVisible(true);
        
        DaoDashboard dash2 = new DaoDashboard();

        JFreeChart chart3 = ChartFactory.createPieChart3D("Quantidade de comodos do projeto", dash2.buscaProQuant(projeto), true, true, true);
        ChartPanel cp3 = new ChartPanel(chart3);

        JInternalFrame jif3 = new JInternalFrame(
            "Comodos do projeto", true, true, true, true);
        
        jif3.add(cp3);
        jif3.pack();
        jif3.setLocation(0, 355);
        jif3.setSize(600, 300);
        jif3.setVisible(true);
        
        
        jdp.add(jif);
        jdp.add(jif2);
        jdp.add(jif3);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
